# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#' @param myarray 2D-Array for melt to use!
#' @return melt_matrix melted matrix!
#' @export
melt_pp <- function(myArray) {
    .Call(`_sestcpp_melt_pp`, myArray)
}

#'
#' @param myarray 2D-Array for melt to use!
#' @return dataframe melted matrix!
#' @export
melt_pp2 <- function(myArray) {
    .Call(`_sestcpp_melt_pp2`, myArray)
}

rcpp_hello_world <- function() {
    .Call(`_sestcpp_rcpp_hello_world`)
}

